### PR TITLE
Repaired DNS options for client

### PR DESCRIPTION
**Pull request by limosek**

### CODE REVIEW

**Comment by ronnylov** [comment]
I got "unknown parameter" when starting lthnvpnd.
Checked my file /etc/lthn/var/vpn_2A/cfg

This line was found:
`push dhcp-option DNS 172.28.0.11`
I beleive it should be
`push "dhcp-option DNS 172.28.0.11"`

**Comment by limosek** [comment]
Sorry, my fault. You are right. Missing quotes in openvpn template file.

**Comment by ronnylov** [comment]
I tested adding quotes in openvpn template file and it works. I also added the push "block-outside-dns" to  openvpn_server.tmpl on my exit node Lethernet FR. It works on Windows clients and the dns is pushed properly.

```
push "{push_dns}"
push "block-outside-dns"
```

**Comment by valiant1x** [comment]
Quotes fixed in my commit. I am not sure about possible cross-platform implications of `push "block-outside-dns"`, as I believe the param is designed for Windows users only. I asked @limosek about it on Slack.

**Comment by ronnylov** [comment]
I did a test with Linux client lthnvpnc and got DNS leak problem there while it was solved on Windows using "block-outside-dns". However it did not seem that this option made any harm either on Linux. We can look for other solutions on Linux. I have no MAC so don't know there.

For reference I found some links how this may be solved on Linux but we need to test.
For systemd > 229: https://github.com/jonathanio/update-systemd-resolved
Older systemd versions: https://github.com/alfredopalhares/openvpn-update-resolv-conf
I have not tested any of these solutions.

**Pull request merged**
